---
name: Build all containers

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'

jobs:
  container-builder:
    strategy:
      fail-fast: false
      matrix:
        image:
          - clientdl
          - fileserver
          - server
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@6eefb174e94bfdeb1cb1caf0a0de19a7634a80d0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%dT%H%M%S')"
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Prep for build
        env:
          MODULUS: ${{ secrets.RS_KEY_MODULUS }}
          EXPONENT: ${{ secrets.RS_KEY_EXPONENT }}
          PRIVATE: ${{ secrets.RS_KEY_PRIVATE }}
        run: |
          mkdir ${{ matrix.image }}/keys
          echo $MODULUS > ${{ matrix.image }}/keys/modulus
          echo $EXPONENT > ${{ matrix.image }}/keys/exponent
          echo $PRIVATE > ${{ matrix.image }}/keys/priv.key
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image }}
          push: true
          tags: |
            jeffcasavant/2006redone-${{ matrix.image }}:latest
            jeffcasavant/2006redone-${{ matrix.image }}:${{ steps.timestamp.outputs.timestamp }}
